### ISSUE TITLE
LICENSE File mising

### ISSUE THREAD

**Issue by agehlers** [bcgov/openconsult#8]
Hi, could you please add a LICENSE file your repo. All repositories in the BCGOV ORG are required to have a LICENSE file. Reference: https://github.com/bcgov/BC-Policy-Framework-For-GitHub/tree/master/BC-Gov-Org-HowTo and https://github.com/bcgov/BC-Policy-Framework-For-GitHub/blob/master/BC-Gov-Org-HowTo/Cheatsheet.md. Thank you.

**Comment by camfindlay** [comment]
+1 a Creative Commons Attribution 4.0 would be ideal ;)

**Comment by agehlers** [comment]
That would work for the context of this repo. Thanks
To add simply do "Add new file" LICENSE , this should give you a drop down of the common license files available, pick one. You also could add a badge/logo  to the readme to get fancy (https://creativecommons.org/about/downloads).

**Comment by hughstimson** [comment]
I have added a separate license file in commit ac1dca89f950a57392906659a09b1f0a8b4f58f4.

@camfindlay yup the existing license is CC BY 4.0.

@agehlers my read of the BC Gov policy framework is that the expected behaviour is to indicate the license with a footer in the readme, which @juhewitt had previously done (including a fancy badge) but I don't suppose there's any harm in also having a LICENSE.md as well.
